<?php

namespace Database\Seeders;

use App\Models\Type;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TypeSeeder extends Seeder
{

    private $type = array(
        array('typeid' => '1', 'text' => 'وقف', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '2', 'text' => 'احوال مال المسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '3', 'text' => 'احوال مال غير المسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '4', 'text' => 'احوال نفس غير مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '5', 'text' => 'احوال نفس مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '6', 'text' => 'اختصام القضاة وأعضاء النيابة', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '7', 'text' => 'ادخال واخراج وارث غير مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '8', 'text' => 'ادخال واخراج وارث مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '9', 'text' => 'استئناف حقوق', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '10', 'text' => 'استئناف احوال شخصية ومواريث', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '11', 'text' => 'استئناف الامور المستعجلة', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '12', 'text' => 'استئناف التماس إعادة نظر تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '13', 'text' => 'استئناف التماس إعادة نظر عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '14', 'text' => 'استئناف التماس إعادة نظر عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '15', 'text' => 'استئناف التماس إعادة نظر مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '16', 'text' => 'استئناف التماس إعادة نظرأحوال', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '17', 'text' => 'استئناف التنفيد', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '18', 'text' => 'استئناف انابات تجارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '19', 'text' => 'استئناف انابات عقارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '20', 'text' => 'استئناف انابات عمالية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '21', 'text' => 'استئناف انابات قضائية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '22', 'text' => 'استئناف انابات قضائية شرعية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '23', 'text' => 'استئناف انابات مدنية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '24', 'text' => 'استئناف أمر على عريضة تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '25', 'text' => 'مكرر', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '26', 'text' => 'استئناف أمر على عريضة عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '27', 'text' => 'استئناف أمر على عريضة عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '28', 'text' => 'استئناف أمر على عريضة مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '29', 'text' => 'استئناف أمور مستعجلة تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '30', 'text' => 'استئناف أمور مستعجلة شرعية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '31', 'text' => 'استئناف أمور مستعجلة عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '32', 'text' => 'استئناف أمور مستعجلة عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '33', 'text' => 'استئناف أمور مستعجلة مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '34', 'text' => 'استئناف تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '35', 'text' => 'استئناف تظلم تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '36', 'text' => 'استئناف تظلم شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '37', 'text' => 'استئناف تظلم عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '38', 'text' => 'استئناف تظلم عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '39', 'text' => 'استئناف تظلم مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '40', 'text' => 'استئناف تنفيذ تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '41', 'text' => 'استئناف تنفيذ شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '42', 'text' => 'استئناف تنفيذ عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '43', 'text' => 'استئناف تنفيذ عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '44', 'text' => 'استئناف تنفيذ مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '45', 'text' => 'استئناف شرعي (قديم)', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '46', 'text' => 'استئناف عقاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '47', 'text' => 'استئناف عمالي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '48', 'text' => 'استئناف مدني', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '49', 'text' => 'اشكالات تجارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '50', 'text' => 'اشكالات شرعية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '51', 'text' => 'اشكالات عقارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '52', 'text' => 'اشكالات عمالية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '53', 'text' => 'اشكالات مدنية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '54', 'text' => 'اشهار إفلاس', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '55', 'text' => 'اعتراض حقوق شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '56', 'text' => 'اعتراض حقوق مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '57', 'text' => 'اعلام شرعي غير مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '58', 'text' => 'اعلام شرعي مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '59', 'text' => 'الاشكالات', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '60', 'text' => 'التماس اعادة نظر', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '61', 'text' => 'التماس اعادة نظر - شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '62', 'text' => 'التماس اعادة نظر تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '63', 'text' => 'التماس اعادة نظر عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '64', 'text' => 'التماس اعادة نظر عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '65', 'text' => 'التماس اعادة نظر مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '66', 'text' => 'التماس إعادة نظر-أحوال', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '67', 'text' => 'التماس إعادة نظر-أحوال شخصية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '68', 'text' => 'التماس إعادة نظر-حقوق', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '69', 'text' => 'التماس إعادة نظر تجاري-استئناف', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '70', 'text' => 'التماس إعادة نظر عقاري-استئناف', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '71', 'text' => 'التماس إعادة نظر عمالي-استئناف', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '72', 'text' => 'التماس إعادة نظر مدني-استئناف', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '73', 'text' => 'التماس إعادة نظر(حقوق)-استئناف', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '74', 'text' => 'الغرامات', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '75', 'text' => 'امر أداء', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '76', 'text' => 'امر على عريضة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '77', 'text' => 'امر على عريضة-استئناف', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '78', 'text' => 'امر على عريضة-تمييز', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '79', 'text' => 'امر على عريضة - شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '80', 'text' => 'امر على عريضة تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '81', 'text' => 'امر على عريضة عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '82', 'text' => 'امر على عريضة عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '83', 'text' => 'امر على عريضة مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '84', 'text' => 'انابات', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '85', 'text' => 'انابات اجرائية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '86', 'text' => 'انابات تجارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '87', 'text' => 'انابات شرعية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '88', 'text' => 'انابات عقارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '89', 'text' => 'انابات عمالية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '90', 'text' => 'انابات مدنية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '91', 'text' => 'اوامر ادارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '92', 'text' => 'اوامر ادارية عقارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '93', 'text' => 'اوامر ادارية مدنية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '94', 'text' => 'بيع عقار مرهون', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '95', 'text' => 'تجاري جزئي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '96', 'text' => 'تجاري جزئي قديم', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '97', 'text' => 'تجاري كلي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '98', 'text' => 'تركات غير مسلمين', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '99', 'text' => 'تركات مسلمين', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '100', 'text' => 'تسوية تركات غير مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '101', 'text' => 'تسوية تركات مسلمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '102', 'text' => 'تسوية تنفيذ أحوال شخصية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '103', 'text' => 'تصديقات', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '104', 'text' => 'تظلم', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '105', 'text' => 'تظلم تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '106', 'text' => 'تظلم شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '107', 'text' => 'تظلم عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '108', 'text' => 'تظلم عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '109', 'text' => 'تظلم مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '110', 'text' => 'تظلم من أمر على عريضة-استئناف', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '111', 'text' => 'تعيين وصي تركة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '112', 'text' => 'تنفيذ احكام المركز المالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '113', 'text' => 'تنفيذ استرداد', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '114', 'text' => 'تنفيذ الاحكام', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '115', 'text' => 'تنفيذ ايجارات', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '116', 'text' => 'تنفيذ أمور مستعجلة', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '117', 'text' => 'تنفيذ أمور مستعجلة تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '118', 'text' => 'تنفيذ أمور مستعجلة شرعي قديم', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '119', 'text' => 'تنفيذ أمور مستعجلة شرعية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '120', 'text' => 'تنفيذ أمور مستعجلة عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '121', 'text' => 'تنفيذ أمور مستعجلة عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '122', 'text' => 'تنفيذ أمور مستعجلة مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '123', 'text' => 'تنفيذ بالرسوم', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '124', 'text' => 'تنفيذ بالرسوم أحوال شخصية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '125', 'text' => 'تنفيذ بالرسوم تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '126', 'text' => 'تنفيذ بالرسوم عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '127', 'text' => 'تنفيذ بالرسوم عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '128', 'text' => 'تنفيذ بالرسوم مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '129', 'text' => 'تنفيذ تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '130', 'text' => 'تنفيذ شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '131', 'text' => 'تنفيذ شرعي قديم', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '132', 'text' => 'تنفيذ عقاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '133', 'text' => 'تنفيذ عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '134', 'text' => 'تنفيذ مدني', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '135', 'text' => 'حجز تحفظي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '136', 'text' => 'حجز تحفظي تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '137', 'text' => 'حجز تحفظي شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '138', 'text' => 'حجز تحفظي عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '139', 'text' => 'حجز تحفظي عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '140', 'text' => 'حجز تحفظي محاكم المركز المالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '141', 'text' => 'حجز تحفظي مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '142', 'text' => 'حجز تحفظي مركبات', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '143', 'text' => 'حقوق شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '144', 'text' => 'حقوق مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '145', 'text' => 'حل وتصفية الشركة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '146', 'text' => 'دعاوى مستعجلة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '147', 'text' => 'دعاوى مستعجلة تجارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '148', 'text' => 'دعاوى مستعجلة شرعية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '149', 'text' => 'دعاوى مستعجلة عمالية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '150', 'text' => 'دعاوى مستعجلة مدنية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '151', 'text' => 'دعاوى موضوعية-تمييز', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '152', 'text' => 'دعاوي مستعجلة عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '153', 'text' => 'ردالقضاةأوالخبراءأوالمحكمين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '155', 'text' => 'طعن أحوال شخصية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '156', 'text' => 'طعن تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '157', 'text' => 'طعن حقـوق', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '158', 'text' => 'طعن عقاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '159', 'text' => 'طعن عمالي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '160', 'text' => 'طعن مدني', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '161', 'text' => 'طلب بيع مال مرهون (تنفيذ)', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '162', 'text' => 'عرض وإيداع', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '163', 'text' => 'عرض وإيداع أحوال شخصية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '164', 'text' => 'عرض وإيداع تجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '165', 'text' => 'عرض وإيداع عقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '166', 'text' => 'عرض وإيداع عمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '167', 'text' => 'عرض وإيداع مدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '168', 'text' => 'عقاري جزئي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '169', 'text' => 'عقاري كلي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '170', 'text' => 'عمالي جزئي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '171', 'text' => 'عمالي كلي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '172', 'text' => 'عمومي شرعي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '173', 'text' => 'غرامات تجارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '174', 'text' => 'غرامات شرعية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '175', 'text' => 'غرامات عقارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '176', 'text' => 'غرامات عمالية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '177', 'text' => 'غرامات مدنية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '178', 'text' => 'لجان تجارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '179', 'text' => 'لجان عقارية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '180', 'text' => 'لجان عمالية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '181', 'text' => 'لجان مدنية', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '182', 'text' => 'مخاصمة', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '183', 'text' => 'مدني جزئي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '184', 'text' => 'مدني جزئي قديم', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '185', 'text' => 'مدني كلي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '186', 'text' => 'مدني وتجاري جزئي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '187', 'text' => 'مدني وتجاري كلي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '188', 'text' => 'مدني وعمالي كلي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '189', 'text' => 'منازعة موضوعية التنفيذ التجاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '190', 'text' => 'منازعة موضوعية التنفيذ العقاري', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '191', 'text' => 'منازعة موضوعية التنفيذ العمالي', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '192', 'text' => 'منازعة موضوعية بالتنفيذ المدني', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '193', 'text' => 'نزاع تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '194', 'text' => 'نزاع تعيين خبرة تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '196', 'text' => 'نزاع تعيين خبرة مدني', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '197', 'text' => 'نزاع عقاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '198', 'text' => 'نزاع مدني', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '199', 'text' => 'نوع مؤقت لتعريف أشخاص ثانويين', 'active' => 'false', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '201', 'text' => 'عاجل', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '202', 'text' => 'تحكيم', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '203', 'text' => 'قضايا إستشارية', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '204', 'text' => 'خدمات', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '205', 'text' => 'عرائض', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '206', 'text' => 'إستشاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '207', 'text' => 'مطالبات بسيطة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '208', 'text' => 'ايجارات', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '209', 'text' => 'جزاء', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '210', 'text' => 'أحوال شخصية غير مسلمين', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '211', 'text' => 'آخر', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),

        array('typeid' => '213', 'text' => 'استئناف جزاء', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '214', 'text' => 'التماس ايجارات', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '215', 'text' => 'اداري كلي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '216', 'text' => 'نقض تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '217', 'text' => 'افلاس', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '218', 'text' => 'حراسة قضائية', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '219', 'text' => 'استشارات ضريبية', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '220', 'text' => 'ايجارات تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '221', 'text' => 'استئناف ايجارات تجاري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '222', 'text' => 'استئناف ايجارات', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '223', 'text' => 'ميراث', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '224', 'text' => 'استئناف إداري', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '225', 'text' => 'إداري أموال', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '226', 'text' => 'تجاري بسيطة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '227', 'text' => 'تسوية الالتزامات المالية', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '228', 'text' => 'استئناف ضريبي', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '229', 'text' => 'تنفيذ أحوال شخصية', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '230', 'text' => 'عمالي بسيطة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '231', 'text' => 'مدني بسيطة', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '232', 'text' => 'استئناف أمر أداء', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '233', 'text' => 'إعسار', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL),
        array('typeid' => '234', 'text' => 'اعسار', 'active' => 'true', 'created' => NULL, 'updated' => NULL, 'deleted' => NULL)
    );

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect($this->type)->each(function ($item) {
            Type::create([
                'id' => $item['typeid'],
                'name' => $item['text'],
                'active' => $item['active'],
            ]);
        });
    }
}
